### ISSUE TITLE
Unexpected baseline memory allocations

### ISSUE THREAD

**Issue by janbruedigam** [tkf/BenchmarkCI.jl#48]
I have a dynamics simulation package (https://github.com/janbruedigam/ConstrainedDynamics.jl) based on StaticArrays for which I'm running benchmark simulations. The main goal for me is to make sure that new commits do not introduce memory allocations as that would drastically reduce performance.

The issue I have is that for a pull request, the target benchmark is correct, but the baseline benchmark is not. For some reason, the baseline benchmark has a large number of allocations even though it did not have these allocations before it was merged into the master. So the judgement tells me the target performs a lot better simply because of the allocations of the baseline, which makes it a problematic comparison.

As an example:
- The benchmark for a pull request: https://github.com/janbruedigam/ConstrainedDynamics.jl/runs/738111902?check_suite_focus=true
- The difference between baseline and target is a single line changed in the readme which should not have an effect: https://github.com/janbruedigam/ConstrainedDynamics.jl/compare/99f9aba...benchmark_alloc_test

**Comment by tkf** [comment]
Benchmark results can have some fluctuations in general. So, I wouldn't worry too much about it. Also, I'm not sure how much BenchmarkCI.jl can help here. It's just running the benchmark as-is using PkgBenchmark.jl.  Maybe you can increase the threshold. But this is more like PkgBenchmark.jl setting.

**Comment by janbruedigam** [comment]
Mmm, so small fluctuations would be fine, but I get more like a 100x difference for exactly the same code (see below). So if this is not a BenchmarkCI.jl bug and both benchmarks are run exactly the same way, I'm not sure how PkgBenchmark.jl causes that difference.

comparison:
![comparison](https://user-images.githubusercontent.com/46260565/83782775-3b61fb80-a690-11ea-96f2-010ef1fd59ae.png)

target:
![target](https://user-images.githubusercontent.com/46260565/83782907-4583fa00-a690-11ea-85fe-2edecabc833a.png)

baseline:
![baseline](https://user-images.githubusercontent.com/46260565/83782951-487eea80-a690-11ea-809f-19929f214010.png)

**Comment by tkf** [comment]
Hmm... I see. That's a big difference. Thanks for quoting the relevant output.

I think the only difference between target and baseline is that tuning is done in the target process. But I think BenchmarkTools.jl tries to run warm-up always.

Maybe the first step is to reproduce this locally. See https://github.com/tkf/BenchmarkCI.jl#running-benchmarkci-interactively.  You can run `rm benchmark/*.json` before `BenchmarkCI.judge()` to make it closer to what happens in the CI.  You can also call `PkgBenchmark.benchmarkpkg` directly and see if it can be reproduced just by PkgBenchmark.

**Comment by janbruedigam** [comment]
I just tried directly calling `PkgBenchmark.benchmarkpkg` with the following code:
```julia
julia> using PkgBenchmark
julia> import ConstrainedDynamics
julia> benchmarkpkg(ConstrainedDynamics)
```

The first call gave the correct results. When I called `benchmarkpkg(ConstrainedDynamics)` again, I got results similar to the bad baseline results above. After deleting the tune.json file, I got the correct results again. 
Could it help if BenchmarkCI.jl deleted the tune.json file after the target benchmarking?

**Comment by tkf** [comment]
Sharing the tuning file is an important design of BenchmarkTools.jl.  So, I don't think it's a valid fix.  If you can reproduce the problem just by `benchmarkpkg`, there is not much BenchmarkCI.jl can do about it.

I think there is a problem in the warm-up stage in BenchmarkTools.jl. If you tune the benchmark in the same process, you already JIT-compiled the function before start running the benchmark. If you have the tuning file, the benchmark is run before JIT-compilation.

You might be able to work around the problem by tweaking the benchmark parameters (e.g., longer `seconds` parameter):

https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#benchmark-parameters

**Comment by janbruedigam** [comment]
I played around a bit with the parameters and I think you're right, the JIT compilation seems to make the difference. 
I think it might be useful to have the option to pass the `retune` kwarg through `BenchmarkCI.judge` to `PkgBenchmark.benchmarkpkg`, not sure how much effort that is for you to implement.

But feel free to close this issue since it's not a BenchmarkCI issue.

**Comment by tkf** [comment]
It might be reasonable to pass-though some keyword arguments to `benchmarkpkg` since there are other useful options.  So let's keep this open.

But I think a better fix would be to add something like `min_warmup_evals` parameter in BenchmarkTools.jl.
